export const MENU_CONFIG = {
	ADMIN: [
		{ key: 'dashboard', label: 'Tổng quan hệ thống', icon: 'dashboard', route: '/admin/dashboard', permissions: ['quan_tri:nguoi_dung'] },
		{ key: 'users', label: 'Quản lý tài khoản', icon: 'team', route: '/admin/users', permissions: ['quan_tri:nguoi_dung'] },
		{ key: 'doctors', label: 'Hồ sơ bác sĩ', icon: 'doctor', route: '/admin/doctors', permissions: ['quan_tri:ho_so_nhan_vien'] },
		{ key: 'staffs', label: 'Hồ sơ nhân viên', icon: 'staff', route: '/admin/staffs', permissions: ['quan_tri:ho_so_nhan_vien'] },
		{ key: 'roles-permissions', label: 'Vai trò và quyền', icon: 'shield', route: '/admin/roles-permissions', permissions: ['quan_tri:vai_tro'] },
		{ key: 'system-config', label: 'Cấu hình hệ thống', icon: 'setting', route: '/admin/system-config', permissions: ['quan_tri:cau_hinh'] },
		{ key: 'reports-appointments', label: 'Báo cáo lịch hẹn', icon: 'file', route: '/admin/reports/appointments', permissions: ['quan_tri:bao_cao'] },
		{ key: 'reports-revenue', label: 'Báo cáo doanh thu', icon: 'chart', route: '/admin/reports/revenue', permissions: ['quan_tri:bao_cao'] },
		{ key: 'doctor-schedule', label: 'Lịch làm việc bác sĩ', icon: 'schedule', route: '/admin/doctor-schedule', permissions: ['quan_tri:lich_lam_viec'] },
	],
	RECEPTIONIST: [
		{ key: 'appointments', label: 'Quản lý lịch hẹn', icon: 'schedule', route: '/staff/appointments', permissions: ['nghiep_vu:quan_ly_lich_hen'] },
		{ key: 'profile', label: 'Hồ sơ nhân viên', icon: 'user', route: '/staff/profile', permissions: ['nhan_vien:read'] },
		{ key: 'account-settings', label: 'Cài đặt tài khoản', icon: 'setting', route: '/staff/account-settings', permissions: ['nguoi_dung:read'] },
		{ key: 'logout', label: 'Đăng xuất', icon: 'logout', route: '/staff/logout' },
	],
	DOCTOR: [
		{ key: 'doctor-info', label: 'Thông tin bác sĩ', icon: 'user', route: '/doctor/thong-tin', permissions: ['nghiep_vu:kham_benh'] },
		{ key: 'patient-management', label: 'Quản lý bệnh nhân', icon: 'team', route: '/doctor/quan-ly-benh-nhan', permissions: ['nghiep_vu:kham_benh'] },
		{ key: 'account-settings', label: 'Cài đặt tài khoản', icon: 'setting', route: '/doctor/account-settings', permissions: ['nguoi_dung:read'] },
		{ key: 'logout', label: 'Đăng xuất', icon: 'logout', route: '/doctor/logout' },
	],
	PATIENT: [
		{ key: 'dashboard', label: 'Tổng quan', icon: 'dashboard', route: '/patient/dashboard', permissions: ['nghiep_vu:dat_lich'] },
		{ key: 'explore-doctors', label: 'Khám phá bác sĩ', icon: 'compass', route: '/patient/kham-pha/explore', permissions: ['bac_si:read'] },
		{ key: 'explore-services', label: 'Khám phá dịch vụ', icon: 'medicine', route: '/patient/kham-pha/services', permissions: ['bac_si:read'] },
		{ key: 'booking', label: 'Đặt lịch', icon: 'calendar', route: '/patient/dat-lich', permissions: ['nghiep_vu:dat_lich'] },
		{ key: 'my-appointments', label: 'Lịch hẹn của tôi', icon: 'schedule', route: '/patient/lich-cua-toi', permissions: ['lich_hen:read'] },
		{ key: 'visit-history', label: 'Lịch sử khám', icon: 'file', route: '/patient/lich-su-kham', permissions: ['phieu_kham:read'] },
		{ key: 'profile', label: 'Hồ sơ bệnh nhân', icon: 'user', route: '/patient/profile', permissions: ['benh_nhan:read'] },
		{ key: 'account', label: 'Tài khoản', icon: 'setting', route: '/patient/account', permissions: ['nguoi_dung:read'] },
		{ key: 'logout', label: 'Đăng xuất', icon: 'logout', route: '/patient/logout' },
	],
	AUTH: [
		{ key: 'landing', label: 'Trang chủ', route: '/' },
		{ key: 'login', label: 'Đăng nhập', route: '/login' },
		{ key: 'register', label: 'Đăng ký', route: '/register' },
	],
}
