<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DichVuSeeder extends Seeder
{
    public function run(): void
    {
        $chuyenKhoaNoi = DB::table('chuyen_khoa')->where('ma_chuyen_khoa', 'CK001')->value('id');
        $chuyenKhoaXn = DB::table('chuyen_khoa')->where('ma_chuyen_khoa', 'CK002')->value('id');
        $chuyenKhoaCdha = DB::table('chuyen_khoa')->where('ma_chuyen_khoa', 'CK003')->value('id');

        DB::table('dich_vu')->upsert([
            [
                'ma_dich_vu' => 'DV001',
                'ten_dich_vu' => 'Xét nghiệm máu tổng quát (CBC)',
                'chuyen_khoa_id' => $chuyenKhoaXn,
                'mo_ta' => 'Nhóm Xét nghiệm',
                'gia_dich_vu' => 100000,
                'thoi_gian_du_kien' => 30,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'xet_nghiem',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV002',
                'ten_dich_vu' => 'Đường huyết',
                'chuyen_khoa_id' => $chuyenKhoaXn,
                'mo_ta' => 'Nhóm Xét nghiệm',
                'gia_dich_vu' => 50000,
                'thoi_gian_du_kien' => 20,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'xet_nghiem',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV003',
                'ten_dich_vu' => 'Mỡ máu',
                'chuyen_khoa_id' => $chuyenKhoaXn,
                'mo_ta' => 'Nhóm Xét nghiệm',
                'gia_dich_vu' => 120000,
                'thoi_gian_du_kien' => 40,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'xet_nghiem',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV004',
                'ten_dich_vu' => 'Chức năng gan',
                'chuyen_khoa_id' => $chuyenKhoaXn,
                'mo_ta' => 'Nhóm Xét nghiệm',
                'gia_dich_vu' => 150000,
                'thoi_gian_du_kien' => 45,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'xet_nghiem',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV005',
                'ten_dich_vu' => 'Chức năng thận',
                'chuyen_khoa_id' => $chuyenKhoaXn,
                'mo_ta' => 'Nhóm Xét nghiệm',
                'gia_dich_vu' => 150000,
                'thoi_gian_du_kien' => 45,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'xet_nghiem',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV006',
                'ten_dich_vu' => 'X-quang phổi',
                'chuyen_khoa_id' => $chuyenKhoaCdha,
                'mo_ta' => 'Nhóm Chẩn đoán hình ảnh',
                'gia_dich_vu' => 120000,
                'thoi_gian_du_kien' => 20,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'chan_doan_hinh_anh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV007',
                'ten_dich_vu' => 'X-quang cột sống',
                'chuyen_khoa_id' => $chuyenKhoaCdha,
                'mo_ta' => 'Nhóm Chẩn đoán hình ảnh',
                'gia_dich_vu' => 150000,
                'thoi_gian_du_kien' => 25,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'chan_doan_hinh_anh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV008',
                'ten_dich_vu' => 'Siêu âm bụng tổng quát',
                'chuyen_khoa_id' => $chuyenKhoaCdha,
                'mo_ta' => 'Nhóm Chẩn đoán hình ảnh',
                'gia_dich_vu' => 200000,
                'thoi_gian_du_kien' => 20,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'chan_doan_hinh_anh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV009',
                'ten_dich_vu' => 'Siêu âm tim',
                'chuyen_khoa_id' => $chuyenKhoaCdha,
                'mo_ta' => 'Nhóm Chẩn đoán hình ảnh',
                'gia_dich_vu' => 350000,
                'thoi_gian_du_kien' => 30,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'chan_doan_hinh_anh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV010',
                'ten_dich_vu' => 'CT Scan não',
                'chuyen_khoa_id' => $chuyenKhoaCdha,
                'mo_ta' => 'Nhóm Chẩn đoán hình ảnh',
                'gia_dich_vu' => 1500000,
                'thoi_gian_du_kien' => 45,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'chan_doan_hinh_anh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV011',
                'ten_dich_vu' => 'Điện tim (ECG)',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Thăm dò chức năng (map enum: khac)',
                'gia_dich_vu' => 80000,
                'thoi_gian_du_kien' => 15,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'khac',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV012',
                'ten_dich_vu' => 'Đo chức năng hô hấp',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Thăm dò chức năng (map enum: khac)',
                'gia_dich_vu' => 200000,
                'thoi_gian_du_kien' => 30,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'khac',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV013',
                'ten_dich_vu' => 'Điện não đồ',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Thăm dò chức năng (map enum: khac)',
                'gia_dich_vu' => 300000,
                'thoi_gian_du_kien' => 40,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'khac',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV014',
                'ten_dich_vu' => 'Truyền dịch',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Thủ thuật',
                'gia_dich_vu' => 150000,
                'thoi_gian_du_kien' => 60,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'thu_thuat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV015',
                'ten_dich_vu' => 'Tiêm kháng sinh',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Thủ thuật',
                'gia_dich_vu' => 50000,
                'thoi_gian_du_kien' => 10,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'thu_thuat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV016',
                'ten_dich_vu' => 'Thay băng vết thương',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Thủ thuật',
                'gia_dich_vu' => 100000,
                'thoi_gian_du_kien' => 20,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'thu_thuat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV017',
                'ten_dich_vu' => 'Khâu vết thương',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Thủ thuật',
                'gia_dich_vu' => 300000,
                'thoi_gian_du_kien' => 30,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'thu_thuat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV018',
                'ten_dich_vu' => 'Khám nội tổng quát',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Khám bệnh',
                'gia_dich_vu' => 100000,
                'thoi_gian_du_kien' => 15,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'kham_benh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV019',
                'ten_dich_vu' => 'Khám tim mạch',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Khám bệnh',
                'gia_dich_vu' => 150000,
                'thoi_gian_du_kien' => 20,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'kham_benh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV020',
                'ten_dich_vu' => 'Khám tai mũi họng',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Khám bệnh',
                'gia_dich_vu' => 150000,
                'thoi_gian_du_kien' => 20,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'kham_benh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV021',
                'ten_dich_vu' => 'Massage trị liệu',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Vật lý trị liệu (map enum: khac)',
                'gia_dich_vu' => 200000,
                'thoi_gian_du_kien' => 45,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'khac',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV022',
                'ten_dich_vu' => 'Điện xung trị liệu',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Vật lý trị liệu (map enum: khac)',
                'gia_dich_vu' => 150000,
                'thoi_gian_du_kien' => 30,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'khac',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_dich_vu' => 'DV023',
                'ten_dich_vu' => 'Tập phục hồi chức năng',
                'chuyen_khoa_id' => $chuyenKhoaNoi,
                'mo_ta' => 'Nhóm Vật lý trị liệu (map enum: khac)',
                'gia_dich_vu' => 250000,
                'thoi_gian_du_kien' => 60,
                'yeu_cau_dac_biet' => null,
                'trang_thai' => 'hoat_dong',
                'loai_dich_vu' => 'khac',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['ma_dich_vu'], ['ten_dich_vu', 'chuyen_khoa_id', 'mo_ta', 'gia_dich_vu', 'thoi_gian_du_kien', 'yeu_cau_dac_biet', 'trang_thai', 'loai_dich_vu', 'updated_at']);
    }
}
