<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhieuKhamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('phieu_kham')->upsert([
            [
                'ma_phieu_kham' => 'PK001',
                'benh_nhan_id' => 1,
                'bac_si_id' => 1,
                'mach' => 80,
                'nhiet_do' => 36.8,
                'huyet_ap' => '120/80',
                'can_nang' => 65,
                'chieu_cao' => 170,
                'trieu_chung' => 'Đau đầu, mệt mỏi',
                'ket_qua_kham' => 'Tim phổi bình thường',
                'chan_doan' => 'Cảm cúm nhẹ',
                'ma_icd10_chinh' => null,
                'tinh_trang' => 'nhe',
                'huong_dieu_tri' => 'Uống thuốc và nghỉ ngơi',
                'loi_dan' => 'Uống nhiều nước',
                'trang_thai' => 'dang_kham',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_phieu_kham' => 'PK004',
                'benh_nhan_id' => 1,
                'bac_si_id' => 2,
                'mach' => 84,
                'nhiet_do' => 37.0,
                'huyet_ap' => '122/82',
                'can_nang' => 65,
                'chieu_cao' => 170,
                'trieu_chung' => 'Đau họng nhẹ buổi sáng',
                'ket_qua_kham' => 'Niêm mạc họng sung huyết nhẹ',
                'chan_doan' => 'Viêm họng nhẹ',
                'ma_icd10_chinh' => null,
                'tinh_trang' => 'nhe',
                'huong_dieu_tri' => 'Điều trị triệu chứng',
                'loi_dan' => 'Giữ ấm vùng cổ, uống nước ấm',
                'trang_thai' => 'hoan_thanh',
                'created_at' => now()->subDays(45),
                'updated_at' => now()->subDays(45),
            ],
            [
                'ma_phieu_kham' => 'PK005',
                'benh_nhan_id' => 1,
                'bac_si_id' => 3,
                'mach' => 88,
                'nhiet_do' => 37.2,
                'huyet_ap' => '124/84',
                'can_nang' => 64,
                'chieu_cao' => 170,
                'trieu_chung' => 'Mệt mỏi, đau đầu về chiều',
                'ket_qua_kham' => 'Chưa ghi nhận bất thường tim phổi',
                'chan_doan' => 'Căng thẳng, rối loạn giấc ngủ',
                'ma_icd10_chinh' => null,
                'tinh_trang' => 'trung_binh',
                'huong_dieu_tri' => 'Điều chỉnh sinh hoạt và nghỉ ngơi',
                'loi_dan' => 'Ngủ đủ giấc, hạn chế caffeine buổi tối',
                'trang_thai' => 'hoan_thanh',
                'created_at' => now()->subDays(18),
                'updated_at' => now()->subDays(18),
            ],
            [
                'ma_phieu_kham' => 'PK002',
                'benh_nhan_id' => 2,
                'bac_si_id' => 2,
                'mach' => 92,
                'nhiet_do' => 37.5,
                'huyet_ap' => '130/85',
                'can_nang' => 58,
                'chieu_cao' => 162,
                'trieu_chung' => 'Sốt nhẹ, đau họng',
                'ket_qua_kham' => 'Viêm họng cấp',
                'chan_doan' => 'Viêm họng',
                'ma_icd10_chinh' => 'J06.9',
                'tinh_trang' => 'trung_binh',
                'huong_dieu_tri' => 'Kháng viêm và nghỉ ngơi',
                'loi_dan' => 'Tái khám nếu sốt kéo dài',
                'trang_thai' => 'cho_ke_don',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_phieu_kham' => 'PK006',
                'benh_nhan_id' => 2,
                'bac_si_id' => 1,
                'mach' => 90,
                'nhiet_do' => 37.6,
                'huyet_ap' => '132/86',
                'can_nang' => 58,
                'chieu_cao' => 162,
                'trieu_chung' => 'Ho khan kéo dài 3 ngày',
                'ket_qua_kham' => 'Phổi thông khí tốt, họng đỏ nhẹ',
                'chan_doan' => 'Nhiễm siêu vi đường hô hấp trên',
                'ma_icd10_chinh' => null,
                'tinh_trang' => 'trung_binh',
                'huong_dieu_tri' => 'Điều trị ngoại trú',
                'loi_dan' => 'Theo dõi nhiệt độ và tái khám khi sốt cao',
                'trang_thai' => 'cho_ke_don',
                'created_at' => now()->subDays(32),
                'updated_at' => now()->subDays(32),
            ],
            [
                'ma_phieu_kham' => 'PK007',
                'benh_nhan_id' => 2,
                'bac_si_id' => 3,
                'mach' => 82,
                'nhiet_do' => 36.9,
                'huyet_ap' => '126/80',
                'can_nang' => 57,
                'chieu_cao' => 162,
                'trieu_chung' => 'Đau bụng lâm râm sau ăn',
                'ket_qua_kham' => 'Bụng mềm, không phản ứng thành bụng',
                'chan_doan' => 'Rối loạn tiêu hóa chức năng',
                'ma_icd10_chinh' => null,
                'tinh_trang' => 'nhe',
                'huong_dieu_tri' => 'Điều chỉnh chế độ ăn',
                'loi_dan' => 'Ăn chín uống sôi, hạn chế đồ cay nóng',
                'trang_thai' => 'hoan_thanh',
                'created_at' => now()->subDays(9),
                'updated_at' => now()->subDays(9),
            ],
            [
                'ma_phieu_kham' => 'PK003',
                'benh_nhan_id' => 3,
                'bac_si_id' => 3,
                'mach' => 76,
                'nhiet_do' => 36.5,
                'huyet_ap' => '118/75',
                'can_nang' => 70,
                'chieu_cao' => 175,
                'trieu_chung' => 'Đau bụng âm ỉ',
                'ket_qua_kham' => 'Theo dõi rối loạn tiêu hóa',
                'chan_doan' => 'Rối loạn tiêu hóa',
                'ma_icd10_chinh' => 'K29.7',
                'tinh_trang' => 'nhe',
                'huong_dieu_tri' => 'Điều chỉnh ăn uống',
                'loi_dan' => 'Hạn chế đồ cay nóng',
                'trang_thai' => 'hoan_thanh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_phieu_kham' => 'PK008',
                'benh_nhan_id' => 3,
                'bac_si_id' => 1,
                'mach' => 78,
                'nhiet_do' => 36.7,
                'huyet_ap' => '118/76',
                'can_nang' => 69,
                'chieu_cao' => 175,
                'trieu_chung' => 'Đau đầu thoáng qua khi làm việc khuya',
                'ket_qua_kham' => 'Thần kinh khu trú âm tính',
                'chan_doan' => 'Đau đầu căng cơ',
                'ma_icd10_chinh' => null,
                'tinh_trang' => 'nhe',
                'huong_dieu_tri' => 'Nghỉ ngơi, giảm căng thẳng',
                'loi_dan' => 'Giãn cơ, ngủ đủ giấc',
                'trang_thai' => 'hoan_thanh',
                'created_at' => now()->subDays(60),
                'updated_at' => now()->subDays(60),
            ],
            [
                'ma_phieu_kham' => 'PK009',
                'benh_nhan_id' => 3,
                'bac_si_id' => 2,
                'mach' => 81,
                'nhiet_do' => 36.8,
                'huyet_ap' => '120/78',
                'can_nang' => 70,
                'chieu_cao' => 175,
                'trieu_chung' => 'Khó tiêu sau bữa tối',
                'ket_qua_kham' => 'Không ghi nhận dấu hiệu cấp cứu',
                'chan_doan' => 'Khó tiêu chức năng',
                'ma_icd10_chinh' => null,
                'tinh_trang' => 'nhe',
                'huong_dieu_tri' => 'Điều chỉnh lối sống và ăn uống',
                'loi_dan' => 'Tránh ăn khuya, chia nhỏ bữa ăn',
                'trang_thai' => 'dang_kham',
                'created_at' => now()->subDays(12),
                'updated_at' => now()->subDays(12),
            ],
        ], ['ma_phieu_kham'], ['benh_nhan_id', 'bac_si_id', 'mach', 'nhiet_do', 'huyet_ap', 'can_nang', 'chieu_cao', 'trieu_chung', 'ket_qua_kham', 'chan_doan', 'ma_icd10_chinh', 'tinh_trang', 'huong_dieu_tri', 'loi_dan', 'trang_thai', 'updated_at']);
    }
}
